integration_name: com.NewRelic.redis

instances:
  - name: redis-server-metrics
    command: metrics
    labels:
      env: production
      role: cache

  #- name: <OTHER INSTANCE IDENTIFIER>
  #  command: inventory
  #  arguments:
  #    arg1: <ARG_VALUE>
  #  labels:
  #    key1: <LABEL_VALUE>
